@baseUrl=http://localhost:8080

### LISTAR
GET {{baseUrl}}/pizzas

### CRIAR
POST {{baseUrl}}/pizzas
Content-Type: application/json

{
  "nome": "calabra",
  "preco": 50.00
}

### ATUALIZAR
PUT {{baseUrl}}/pizzas/4
Content-Type: application/json

{
  "nome": "Doce",
  "preco": 55.00
}


### DELETAR
DELETE  {{baseUrl}}/pizzas/4